print("input name1 then name2")
#name1 = str(input())
name1 = str('TJ')
#name2 = str(input())
name2 = str('Christopher Thompson III')
name = '{}{}'.format(name1, name2)
length1 = int(len(name1)+4)
length2 = int(len(name2)+4)
print(("*" * length1)+("  ")+("*" * length2))
print("*", name1, "*  *", name2, "*")
print(("*" * length1)+("  ")+("*" * length2))
